//> using scala 3.4.2
//> using jsVersion 1.16.0
//> using jsMode full
//> using jsModuleKind es
//> using jsModuleSplitStyleStr smallestmodules
//> using dep org.scala-js:scalajs-library_2.13:1.16.0
//> using file src/libs/audio.scala
//> using file src/test2.scala
//> using file src/test.scala
